# Site settings
title: Tizen Ye's private cyberspace
email: yzs981130@126.com
description: > # this means to ignore newlines until "baseurl:"
  The awesome personal page of Tizen Ye would like to show you a new world as he hoped.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yzs981130
github_username:  yzs981130

# Build settings
markdown: rdiscount
highlighter: rouge
